'use client';
import {useEffect,useState} from 'react';
type Booking={id:string;customer:string;service_name:string;duration:number;date:string;time:string;vehicle:string;plate:string;status:string};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
function calendar(b:Booking){const start=new Date(`${b.date}T${b.time}:00-03:00`),end=new Date(start.getTime()+b.duration*60000);const stamp=(d:Date)=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');const escaped=(v:string)=>v.replace(/[\\,;\n]/g,' ');return `BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Duu Jato//Agendamento//PT-BR\r\nBEGIN:VEVENT\r\nUID:${b.id}@duujato\r\nDTSTAMP:${stamp(new Date())}\r\nDTSTART:${stamp(start)}\r\nDTEND:${stamp(end)}\r\nSUMMARY:${escaped(b.service_name)} - Duu Jato\r\nDESCRIPTION:${escaped('Agendamento sujeito a confirmação. Veículo: '+b.vehicle)}\r\nBEGIN:VALARM\r\nACTION:DISPLAY\r\nDESCRIPTION:Lembrete Duu Jato: seu agendamento é amanhã\r\nTRIGGER:-P1D\r\nEND:VALARM\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n`}
export default function ManageBooking(){const [token,setToken]=useState(''),[booking,setBooking]=useState<Booking|null>(null),[hours,setHours]=useState<string[]>([]),[date,setDate]=useState(''),[time,setTime]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{const t=new URLSearchParams(window.location.search).get('token')||'';setToken(t);fetch('/api/manage?token='+encodeURIComponent(t)).then(async r=>{const result=await r.json() as Booking & {error?:string};if(!r.ok)throw new Error(result.error||'Não foi possível carregar.');setBooking(result)}).catch(e=>setError(e instanceof Error?e.message:'Link inválido.'))},[]);
  useEffect(()=>{if(!booking||!date){setHours([]);return}let active=true;fetch('/api/manage/availability?token='+encodeURIComponent(token)+'&date='+date).then(async r=>{const result=await r.json() as string[] & {error?:string};if(!r.ok)throw new Error(result.error||'Não foi possível consultar horários.');if(active)setHours(result)}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Não foi possível consultar horários.')});return()=>{active=false}},[date,booking,token]);
  async function change(action:'cancel'|'reschedule'){if(action==='cancel'&&!confirm('Cancelar este agendamento e liberar o horário?'))return;setBusy(true);setError('');setMessage('');try{const response=await fetch('/api/manage?token='+encodeURIComponent(token),{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({action,date,time})});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||'Não foi possível atualizar.');const refreshed=await fetch('/api/manage?token='+encodeURIComponent(token)).then(r=>r.json() as Promise<Booking>);setBooking(refreshed);setDate('');setTime('');setMessage(action==='cancel'?'Agendamento cancelado.':'Novo horário solicitado. Aguarde a confirmação do lava-jato.')}catch(e){setError(e instanceof Error?e.message:'Não foi possível atualizar.')}finally{setBusy(false)}}
  function download(){if(!booking)return;const url=URL.createObjectURL(new Blob([calendar(booking)],{type:'text/calendar;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='duujato-agendamento.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  return <><header className="top shell"><a className="brand" href="/">DUU<span>JATO</span></a><a href="/">Novo agendamento</a></header><main className="shell admin"><p className="eyebrow">MEU AGENDAMENTO</p><h1>Confira seu horário</h1>{error&&<div className="notice error" role="alert">{error}</div>}{message&&<div className="notice success" role="status">{message}</div>}{booking&&<div className="card manage-card"><h2>{booking.service_name}</h2><p>{booking.customer} · {booking.vehicle} · {booking.plate}</p><p><strong>{new Date(booking.date+'T12:00:00').toLocaleDateString('pt-BR')} às {booking.time}</strong> · {booking.status==='pending'?'Aguardando confirmação':booking.status==='confirmed'?'Confirmado':booking.status==='cancelled'?'Cancelado':'Concluído'}</p><div className="actions"><button type="button" onClick={download}>Adicionar ao calendário</button></div>{['pending','confirmed'].includes(booking.status)&&<><hr/><h3>Precisa de outro horário?</h3><p className="muted">Ao reagendar, o novo horário volta para confirmação.</p><div className="field-grid"><label className="field">Nova data<input type="date" min={today()} value={date} onChange={e=>{setDate(e.target.value);setTime('')}}/></label><label className="field">Novo horário<select value={time} onChange={e=>setTime(e.target.value)}><option value="">Selecione</option>{hours.map(h=><option key={h}>{h}</option>)}</select></label></div><div className="actions" style={{marginTop:18}}><button disabled={busy||!date||!time} className="primary-action" onClick={()=>change('reschedule')}>Solicitar reagendamento</button><button disabled={busy} onClick={()=>change('cancel')}>Cancelar agendamento</button></div></>}</div>}</main></>}
