import {db,fail,owner} from '@/lib/booking';
import {isOwnerEmail,normalizeEmail,validEmail} from '@/lib/access';
import {employeeAuth,invitationsConfigured,sendEmployeeAccess,temporaryPassword} from '@/lib/employee-provisioning';
export async function GET(){if(!await owner())return fail('Apenas o administrador pode gerenciar funcionários.',403);try{return Response.json({accounts:(await db().prepare('SELECT email,created_at FROM admin_accounts ORDER BY email').all()).results,invitationsConfigured:invitationsConfigured()})}catch{return fail('Não foi possível carregar os funcionários.',503)}}
export async function POST(request:Request){if(!await owner())return fail('Acesso restrito ao administrador.',403);let email:string;try{email=normalizeEmail(((await request.json()) as {email?:string}).email)}catch{return fail('Dados inválidos.')}if(!validEmail(email))return fail('Informe um e-mail válido.');if(isOwnerEmail(email))return fail('Esta é a conta administradora e não pode ser cadastrada como funcionário.');if(!invitationsConfigured())return fail('O envio de acessos por e-mail ainda precisa ser configurado. Nenhuma conta foi criada.',503);
try{if(await db().prepare('SELECT email FROM admin_accounts WHERE email=?').bind(email).first())return fail('Este funcionário já está cadastrado.',409)}catch{return fail('Não foi possível consultar os funcionários.',503)}
const auth=employeeAuth(),password=temporaryPassword();const {data,error}=await auth.auth.admin.createUser({email,password,email_confirm:true,app_metadata:{role:'employee'}});
if(error||!data.user)return fail('Não foi possível criar a conta. Se este e-mail já possui uma conta, utilize outro e-mail ou contate o suporte.',409);
try{await sendEmployeeAccess(email,password,data.user.id);await db().prepare('INSERT INTO admin_accounts (email,created_at) VALUES (?,?)').bind(email,new Date().toISOString()).run();return Response.json({ok:true,message:'Funcionário cadastrado. O e-mail com a senha inicial foi enviado.'},{status:201})}catch{const rollback=await auth.auth.admin.deleteUser(data.user.id);if(rollback.error)console.error('Falha ao limpar cadastro incompleto de funcionário.');return fail('O cadastro não foi concluído e nenhum acesso foi liberado. Verifique o serviço de e-mail antes de tentar novamente.',503)}}
export async function DELETE(request:Request){if(!await owner())return fail('Acesso restrito ao administrador.',403);const email=normalizeEmail(new URL(request.url).searchParams.get('email'));if(!validEmail(email)||isOwnerEmail(email))return fail('Conta inválida.');try{await db().prepare('DELETE FROM admin_accounts WHERE email=?').bind(email).run();return Response.json({ok:true})}catch{return fail('Não foi possível remover o acesso.',503)}}
