'use client';
import {useCallback,useEffect,useState} from 'react';

type Entry={booking_id:string;status:string;attempts:number;error:string|null;created_at:string;updated_at:string;customer:string;date:string;time:string};
type State={configured:boolean;enabled:boolean;recipient:string|null;entries:Entry[]};
const labels:Record<string,string>={pending:'Aguardando envio',sending:'Envio iniciado',accepted:'Aceito pela Meta',failed:'Falha no envio',uncertain:'Envio não confirmado',cancelled:'Agendamento cancelado — aviso não enviado'};
export default function WhatsappPanel(){
  const [data,setData]=useState<State|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState('');
  const refresh=useCallback(async()=>{try{const response=await fetch('/api/admin/whatsapp');const result=await response.json();if(!response.ok)throw Error(result.error||'Não foi possível carregar os avisos.');setData(result);setError('')}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar.')}},[]);
  useEffect(()=>{void refresh()},[refresh]);
  async function retry(id:string){setBusy(id);setError('');try{const response=await fetch('/api/admin/whatsapp',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id})});const result=await response.json();if(!response.ok)throw Error(result.error);await refresh()}catch(e){setError(e instanceof Error?e.message:'Não foi possível enviar.')}finally{setBusy('')}}
  return <><div className="tab-heading"><div><h2>Avisos no WhatsApp</h2><p className="muted">Receba um aviso quando um cliente fizer um agendamento pelo site.</p></div><button type="button" className="secondary-link" onClick={()=>void refresh()}>Atualizar histórico</button></div>{error&&<p className="notice error" role="alert">{error}</p>}{data&&<><div className="card"><h3>{data.configured?'Envio automático ativado':'Conexão aguardando configuração'}</h3>{data.configured?<p>Os avisos são enviados para {data.recipient}. O histórico confirma a aceitação pela Meta; a entrega é conferida no WhatsApp.</p>:<p>Para ativar, conecte uma conta WhatsApp Business Platform, cadastre o número do dono como destinatário e aprove o modelo de aviso na Meta. A conexão é configurada pelo responsável pelo sistema.</p>}<p className="muted">Cada aviso inclui cliente, serviço, data, horário, veículo e placa. Apenas novos agendamentos online geram avisos após a ativação.</p></div><div className="admin-list">{data.entries.length?data.entries.map(entry=><div className="card appointment" key={entry.booking_id}><div><h3>{entry.customer}</h3><p>{new Date(entry.date+'T12:00:00').toLocaleDateString('pt-BR')} às {entry.time}</p><p>{labels[entry.status]||entry.status} · Tentativas: {entry.attempts}</p>{entry.error&&<p>{entry.error}</p>}{entry.status==='sending'&&<p className="muted">Se o estado persistir, confira o WhatsApp e solicite a verificação do envio.</p>}</div>{data.configured&&['pending','failed'].includes(entry.status)&&entry.attempts<3&&<button type="button" className="primary-action" disabled={!!busy} onClick={()=>void retry(entry.booking_id)}>{busy===entry.booking_id?'Enviando…':'Tentar enviar'}</button>}</div>):<p className="empty">Nenhum aviso registrado.</p>}</div></>}</>
}
