import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import vm from 'node:vm';
import ts from 'typescript';
const require=createRequire(import.meta.url);
function load(path,mocks={}){const source=readFileSync(new URL('../'+path,import.meta.url),'utf8');const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const module={exports:{}};vm.runInNewContext(code,{module,exports:module.exports,require:name=>mocks[name]??require(name),Response,URL,console,process,crypto:globalThis.crypto});return module.exports}
const access=load('lib/access.ts');
function fixture({owner=true,ready=true,exists=false,mailFails=false,dbFails=false}={}){const calls=[];const db=()=>({prepare:sql=>({bind:()=>({first:async()=>exists?{email:'worker@example.com'}:null,run:async()=>{calls.push('grant');if(dbFails)throw Error('db')}})})});const auth={auth:{admin:{createUser:async()=>{calls.push('create');return {data:{user:{id:'employee-id'}},error:null}},deleteUser:async()=>{calls.push('rollback');return {error:null}}}}};const route=load('app/api/admin/accounts/route.ts',{'@/lib/booking':{owner:async()=>owner,db,fail:(error,status=400)=>Response.json({error},{status})},'@/lib/access':access,'@/lib/employee-provisioning':{employeeAuth:()=>auth,invitationsConfigured:()=>ready,temporaryPassword:()=> 'TEST-SECRET-NEVER-RETURN',sendEmployeeAccess:async()=>{calls.push('send');if(mailFails)throw Error('mail')}}});return {route,calls}}
const request=email=>({json:async()=>({email})});
test('employee cannot provision another employee',async()=>{const {route,calls}=fixture({owner:false});assert.equal((await route.POST(request('worker@example.com'))).status,403);assert.deepEqual(calls,[])});
test('owner cannot be added as employee',async()=>{const {route,calls}=fixture();assert.equal((await route.POST(request(' LUANVICTORLCST12@GMAIL.COM '))).status,400);assert.deepEqual(calls,[])});
test('missing email configuration creates no account',async()=>{const {route,calls}=fixture({ready:false});assert.equal((await route.POST(request('worker@example.com'))).status,503);assert.deepEqual(calls,[])});
test('existing employee is not recreated or reset',async()=>{const {route,calls}=fixture({exists:true});assert.equal((await route.POST(request('worker@example.com'))).status,409);assert.deepEqual(calls,[])});
test('email acceptance precedes access grant and API never exposes password',async()=>{const {route,calls}=fixture();const response=await route.POST(request('worker@example.com'));assert.equal(response.status,201);assert.deepEqual(calls,['create','send','grant']);assert.ok(!(await response.text()).includes('TEST-SECRET'))});
test('failed email cleans up new auth account without granting access',async()=>{const {route,calls}=fixture({mailFails:true});assert.equal((await route.POST(request('worker@example.com'))).status,503);assert.deepEqual(calls,['create','send','rollback'])});
test('failed database grant cleans up new auth account',async()=>{const {route,calls}=fixture({dbFails:true});assert.equal((await route.POST(request('worker@example.com'))).status,503);assert.deepEqual(calls,['create','send','grant','rollback'])});
test('public signup is refused before calling Supabase',async()=>{const route=load('app/api/auth/route.ts',{'@supabase/ssr':{createServerClient:()=>{throw Error('must not be called')}},'next/server':{NextResponse:Response},'@/lib/booking':{},'@/lib/access':access});const response=await route.POST({json:async()=>({action:'signup',email:'worker@example.com',password:'test'})});assert.equal(response.status,403)});
for(const [file,method] of [['services','POST'],['services','PATCH'],['settings','PUT'],['settings','POST'],['settings','DELETE']])test(`employee cannot mutate ${file} via ${method}`,async()=>{const route=load(`app/api/admin/${file}/route.ts`,{'@/lib/booking':{admin:async()=>true,owner:async()=>false,fail:(error,status=400)=>Response.json({error},{status})}});assert.equal((await route[method]({})).status,403)});
test('Gmail sends credentials only to employee and confirms recipient acceptance',async()=>{let sent,closed=false;const provisioning=load('lib/employee-provisioning.ts',{'./access':access,nodemailer:{default:{createTransport:()=>({sendMail:async message=>{sent=message;return {accepted:['worker@example.com'],messageId:'mail-id'}},close:()=>{closed=true}})}}});process.env.GMAIL_APP_PASSWORD='test-app-password';assert.equal(await provisioning.sendEmployeeAccess('worker@example.com','TEST-INITIAL-PASSWORD','employee-id'),'mail-id');assert.equal(sent.to,'worker@example.com');assert.equal(sent.from.address,access.OWNER_EMAIL);assert.ok(sent.text.includes('TEST-INITIAL-PASSWORD'));assert.ok(closed);delete process.env.GMAIL_APP_PASSWORD});
test('Gmail rejection is treated as invitation failure',async()=>{const provisioning=load('lib/employee-provisioning.ts',{'./access':access,nodemailer:{default:{createTransport:()=>({sendMail:async()=>({accepted:[],messageId:'mail-id'}),close:()=>{}})}}});process.env.GMAIL_APP_PASSWORD='test-app-password';await assert.rejects(provisioning.sendEmployeeAccess('worker@example.com','TEST-PASSWORD','id'));delete process.env.GMAIL_APP_PASSWORD});
for(const [method,url] of [['GET','https://duujato.vercel.app/api/admin/cash'],['GET','https://duujato.vercel.app/api/admin/cash?format=csv'],['POST','https://duujato.vercel.app/api/admin/cash'],['DELETE','https://duujato.vercel.app/api/admin/cash']])test(`employee cannot access financial route ${method} ${url}`,async()=>{const route=load('app/api/admin/cash/route.ts',{'@/lib/booking':{admin:async()=>true,owner:async()=>false,db:()=>{throw Error('financial database must not be read')},fail:(error,status=400)=>Response.json({error},{status})}});assert.equal((await route[method]({url})).status,403)});
for(const isOwner of [false,true])test(`${isOwner?'owner':'employee'} agenda returns only permitted data`,async()=>{let sql;const route=load('app/api/admin/bookings/route.ts',{'@/lib/booking':{admin:async()=>true,owner:async()=>isOwner,db:()=>({prepare:query=>{sql=query;return {all:async()=>({results:[isOwner?{id:'booking',customer:'Cliente',paid_cents:5000}:{id:'booking',customer:'Cliente'}]})}}}),fail:(error,status=400)=>Response.json({error},{status})}});const response=await route.GET();assert.equal(response.status,200);const rows=await response.json();assert.equal(rows[0].customer,'Cliente');assert.equal('paid_cents' in rows[0],isOwner);assert.equal(sql.includes('cash_entries'),isOwner);assert.equal(sql.includes('b.*'),isOwner)});
test('owner retains access to financial summary',async()=>{const route=load('app/api/admin/cash/route.ts',{'@/lib/booking':{owner:async()=>true,localNow:()=>({today:'2026-09-30'}),db:()=>({prepare:sql=>({bind:()=>({all:async()=>({results:sql.includes('GROUP BY type')?[{type:'income',total:5000},{type:'expense',total:1000}]:[]})})})}),fail:(error,status=400)=>Response.json({error},{status})}});const response=await route.GET({url:'https://duujato.vercel.app/api/admin/cash'});assert.equal(response.status,200);assert.equal((await response.json()).balance,4000)});
