import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import vm from 'node:vm';
import ts from 'typescript';
function load(path,mocks,context={}){const code=ts.transpileModule(readFileSync(new URL('../'+path,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const module={exports:{}};vm.runInNewContext(code,{module,exports:module.exports,require:name=>mocks[name],Response,URL,console,process,crypto:globalThis.crypto,...context});return module.exports}
function fixture({owner=true,failPayment=false}={}){
  const sql=new DatabaseSync(':memory:');
  sql.exec(readFileSync(new URL('../database/vercel-schema.sql',import.meta.url),'utf8').split('-- O browser')[0]);
  sql.exec("INSERT INTO services VALUES ('service','Lavagem completa','',60,5000,1,0);INSERT INTO business_settings (id,capacity) VALUES (1,1)");
  // Exercise the production adapter and its transaction boundary with a local SQL engine.
  const client={unsafe:async(query,args)=>{if(failPayment&&query.startsWith('INSERT INTO cash_entries'))throw Error('cash write failed');const statement=sql.prepare(query.replace(/\$\d+/g,'?'));try{if(/^SELECT/i.test(query))return statement.all(...args);const result=statement.run(...args);return Object.assign([],{count:Number(result.changes)})}catch(error){if(error.message.includes('UNIQUE'))error.code='23505';throw error}},begin:async fn=>{sql.exec('BEGIN');try{const result=await fn(client);sql.exec('COMMIT');return result}catch(error){sql.exec('ROLLBACK');throw error}}};
  const database=load('lib/database.ts',{postgres:{default:()=>client}},{process:{env:{DATABASE_URL:'test-only'}}});
  const initialized=database.db().prepare('SELECT 1').all();
  const access=load('lib/access.ts',{});
  const booking=load('lib/booking.ts',{'./database':database,'./access':access,'./auth':{getAccountUser:async()=>({email:owner?access.OWNER_EMAIL:'worker@example.com'})}});
  const manual=load('lib/manual-booking.ts',{'./booking':booking});
  const body={id:'11111111-1111-4111-8111-111111111111',service:'service',date:booking.localNow().today,time:'08:00',customer:'Cliente teste',phone:'',vehicle:'Honda Civic',plate:'ABC1D23',status:'confirmed',paid:true,amount_cents:4500,payment_method:'Pix'};
  return {sql,initialized,body,post:patch=>manual.createManualBooking({json:async()=>({...body,...patch})})};
}
test('only owner can create manual appointments and payments',async()=>{const f=fixture({owner:false});await f.initialized;assert.equal((await f.post()).status,403);assert.equal(f.sql.prepare('SELECT COUNT(*) AS count FROM bookings').get().count,0);f.sql.close()});
test('walk-in in an elapsed interval saves booking, slots and linked payment together',async()=>{const f=fixture();await f.initialized;assert.equal((await f.post()).status,201);const b=f.sql.prepare('SELECT * FROM bookings').get(),cash=f.sql.prepare('SELECT * FROM cash_entries').get();assert.equal(b.status,'confirmed');assert.equal(b.phone,'');assert.equal(cash.amount_cents,4500);assert.equal(cash.booking_id,b.id);assert.equal(cash.category,'Serviços');assert.equal(f.sql.prepare('SELECT COUNT(*) AS count FROM occupied_slots').get().count,2);f.sql.close()});
test('unpaid completed service creates no cash income',async()=>{const f=fixture();await f.initialized;assert.equal((await f.post({paid:false,status:'completed',amount_cents:undefined})).status,201);assert.equal(f.sql.prepare('SELECT status FROM bookings').get().status,'completed');assert.equal(f.sql.prepare('SELECT COUNT(*) AS count FROM cash_entries').get().count,0);f.sql.close()});
test('repeated submission does not duplicate or modify the payment',async()=>{const f=fixture();await f.initialized;await f.post();const retry=await f.post({amount_cents:9900,paid:false});assert.equal(retry.status,200);assert.equal((await retry.json()).paid,true);assert.equal(f.sql.prepare('SELECT COUNT(*) AS count FROM bookings').get().count,1);assert.equal(f.sql.prepare('SELECT COUNT(*) AS count FROM cash_entries').get().count,1);assert.equal(f.sql.prepare('SELECT amount_cents FROM cash_entries').get().amount_cents,4500);f.sql.close()});
test('full bay refuses another appointment without financial changes',async()=>{const f=fixture();await f.initialized;await f.post();assert.equal((await f.post({id:'22222222-2222-4222-8222-222222222222'})).status,409);assert.equal(f.sql.prepare('SELECT COUNT(*) AS count FROM cash_entries').get().count,1);f.sql.close()});
test('cash failure rolls back appointment and occupied slots',async()=>{const f=fixture({failPayment:true});await f.initialized;assert.equal((await f.post()).status,503);for(const table of ['bookings','occupied_slots','cash_entries'])assert.equal(f.sql.prepare(`SELECT COUNT(*) AS count FROM ${table}`).get().count,0);f.sql.close()});
test('closed date, break and end of day refuse appointments',async()=>{const f=fixture();await f.initialized;f.sql.prepare('INSERT INTO closed_dates VALUES (?,?)').run(f.body.date,'Fechado');assert.equal((await f.post()).status,409);f.sql.exec('DELETE FROM closed_dates');const day=new Date(f.body.date+'T12:00:00Z').getUTCDay();f.sql.prepare('INSERT INTO weekly_hours VALUES (?,1,?,?,?,?)').run(day,'08:00','18:00','12:00','13:00');assert.equal((await f.post({time:'12:00'})).status,409);assert.equal((await f.post({time:'17:30'})).status,409);assert.equal(f.sql.prepare('SELECT COUNT(*) AS count FROM bookings').get().count,0);f.sql.close()});
test('invalid payment, phone and inactive service never write bookings',async()=>{const f=fixture();await f.initialized;for(const patch of [{amount_cents:0},{amount_cents:1.5},{payment_method:'invalid'},{phone:'123'}])assert.equal((await f.post(patch)).status,400);f.sql.exec("UPDATE services SET active=0");assert.equal((await f.post()).status,400);assert.equal(f.sql.prepare('SELECT COUNT(*) AS count FROM bookings').get().count,0);f.sql.close()});
