import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
import {DatabaseSync} from 'node:sqlite';
function load(path,mocks={},context={}){const code=ts.transpileModule(readFileSync(new URL('../'+path,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const module={exports:{}};vm.runInNewContext(code,{module,exports:module.exports,require:n=>mocks[n],Response,URL,AbortSignal,console,crypto:globalThis.crypto,...context});return module.exports}
const env={WHATSAPP_ENABLED:'true',VERCEL_ENV:'production',WHATSAPP_ACCESS_TOKEN:'test-secret',WHATSAPP_PHONE_NUMBER_ID:'123456',WHATSAPP_OWNER_PHONE:'5527999999999',WHATSAPP_TEMPLATE_NAME:'duujato_novo_agendamento',WHATSAPP_API_VERSION:'v99.0'};
function fixture({environment={},response={ok:true,status:200,json:async()=>({messages:[{id:'wamid.test'}]})},throws=false}={}){
 const sql=new DatabaseSync(':memory:');sql.exec(readFileSync(new URL('../database/vercel-schema.sql',import.meta.url),'utf8').split('-- O browser')[0]);
 sql.prepare('INSERT INTO bookings (id,service_id,service_name,duration,date,time,customer,phone,vehicle,plate,status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)').run('booking','s','Lavagem completa',45,'2026-10-10','09:00','Cliente\nExemplo','27999999999','Honda Civic','ABC1D23','pending','today');
 sql.prepare('INSERT INTO whatsapp_notifications (booking_id,recipient,created_at,updated_at) VALUES (?,?,?,?)').run('booking',env.WHATSAPP_OWNER_PHONE,'today','today');
 const db=()=>({prepare:query=>({bind:(...args)=>({first:async()=>sql.prepare(query).get(...args)||null,run:async()=>sql.prepare(query).run(...args),all:async()=>({results:sql.prepare(query).all(...args)})})})});
 const calls=[];const api=load('lib/whatsapp.ts',{'./database':{db}},{process:{env:{...env,...environment}},fetch:async(url,options)=>{calls.push({url,options});if(throws)throw Error('timeout');return response}});
 return {sql,api,calls,row:()=>sql.prepare('SELECT * FROM whatsapp_notifications').get()};
}
test('WhatsApp is inactive without activation or in previews',async()=>{for(const environment of [{WHATSAPP_ENABLED:'false'},{VERCEL_ENV:'preview'},{WHATSAPP_ACCESS_TOKEN:''},{WHATSAPP_OWNER_PHONE:'invalid'}]){const f=fixture({environment});assert.equal(await f.api.dispatchWhatsapp('booking'),'disabled');assert.equal(f.calls.length,0);assert.equal(f.row().status,'pending');f.sql.close()}});
test('successful sends use owner destination and template fields exactly once',async()=>{const f=fixture();assert.equal(await f.api.dispatchWhatsapp('booking'),'accepted');assert.equal(await f.api.dispatchWhatsapp('booking'),'unchanged');assert.equal(f.calls.length,1);const body=JSON.parse(f.calls[0].options.body);assert.equal(body.to,env.WHATSAPP_OWNER_PHONE);assert.equal(body.template.language.code,'pt_BR');assert.deepEqual(body.template.components[0].parameters.map(p=>p.text),['Cliente Exemplo','Lavagem completa','10/10/2026','09:00','Honda Civic','ABC1D23']);assert.equal(f.row().message_id,'wamid.test');f.sql.close()});
test('atomic claim prevents simultaneous duplicate messages',async()=>{const f=fixture();await Promise.all([f.api.dispatchWhatsapp('booking'),f.api.dispatchWhatsapp('booking')]);assert.equal(f.calls.length,1);assert.equal(f.row().attempts,1);f.sql.close()});
test('explicit rejection records a safe error and permits only three attempts',async()=>{const f=fixture({response:{ok:false,status:400,json:async()=>({error:{code:132001,message:'sensitive-token-test-secret'}})}});for(let i=0;i<3;i++)assert.equal(await f.api.dispatchWhatsapp('booking'),'failed');assert.equal(await f.api.dispatchWhatsapp('booking'),'unchanged');assert.equal(f.calls.length,3);assert.ok(f.row().error.includes('132001'));assert.ok(!f.row().error.includes('test-secret'));f.sql.close()});
test('uncertain network result is not retried to avoid duplicate sends',async()=>{const f=fixture({throws:true});assert.equal(await f.api.dispatchWhatsapp('booking'),'uncertain');assert.equal(await f.api.dispatchWhatsapp('booking'),'unchanged');assert.equal(f.calls.length,1);f.sql.close()});
test('cancelled appointments do not send stale new-booking notices',async()=>{const f=fixture();f.sql.exec("UPDATE bookings SET status='cancelled'");assert.equal(await f.api.dispatchWhatsapp('booking'),'cancelled');assert.equal(f.calls.length,0);f.sql.close()});
test('staff cannot consult or retry owner WhatsApp notices',async()=>{const api=load('app/api/admin/whatsapp/route.ts',{'@/lib/booking':{owner:async()=>false,fail:(error,status=400)=>Response.json({error},{status})},'@/lib/whatsapp':{}});assert.equal((await api.GET()).status,403);assert.equal((await api.POST({json:async()=>({id:'anything'})})).status,403)});
function publicRoute({configured=true,commitFails=false,afterFails=false}={}){const statements=[],jobs=[],dispatch=[];let committed=false;const booking={available:async()=>['09:00'],freeBay:async()=>1,slotsFor:()=>['09:00','09:30'],tokenHash:async()=> 'hash',validDate:()=>true,validClock:()=>true,fail:(error,status=400)=>Response.json({error},{status}),db:()=>({prepare:query=>({bind:(...args)=>({query,args,first:async()=>({id:'s',name:'Lavagem',duration:45})})}),batch:async list=>{if(commitFails)throw Error('db failure');statements.push(...list);committed=true}})};const api=load('app/api/bookings/route.ts',{'@/lib/booking':booking,'next/server':{after:fn=>{if(afterFails)throw Error('scheduler');jobs.push(fn)}},'@/lib/whatsapp':{whatsappConfiguration:()=>({configured,recipient:env.WHATSAPP_OWNER_PHONE}),dispatchWhatsapp:async id=>{assert.equal(committed,true);dispatch.push(id)}}});return {api,statements,jobs,dispatch}}
const request={json:async()=>({date:'2026-10-10',time:'09:00',service:'s',customer:'Cliente Exemplo',phone:'27999999999',vehicle:'Honda Civic',plate:'ABC1D23'})};
test('public booking queues notification atomically then sends after commit',async()=>{const f=publicRoute();const response=await f.api.POST(request);assert.equal(response.status,201);assert.equal(f.statements.filter(x=>x.query.includes('whatsapp_notifications')).length,1);assert.equal(f.dispatch.length,0);await f.jobs[0]();assert.equal(f.dispatch.length,1)});
test('failed booking writes never schedule WhatsApp messages',async()=>{const f=publicRoute({commitFails:true});assert.equal((await f.api.POST(request)).status,409);assert.equal(f.jobs.length,0);assert.equal(f.dispatch.length,0)});
test('disabled integration and scheduling failure preserve successful booking response',async()=>{const disabled=publicRoute({configured:false});assert.equal((await disabled.api.POST(request)).status,201);assert.ok(!disabled.statements.some(x=>x.query.includes('whatsapp_notifications')));assert.equal(disabled.jobs.length,0);const scheduling=publicRoute({afterFails:true});assert.equal((await scheduling.api.POST(request)).status,201)});
