import type {Metadata} from 'next';
import {db,defaultHours,type Hours} from '@/lib/booking';
import Booking from './booking';
import {BOOKING_URL} from '@/lib/site';
export const dynamic='force-dynamic';
const days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
async function business(){try{const [profile,hours]=await Promise.all([db().prepare('SELECT name,phone,address FROM business_settings WHERE id=1').first<{name:string;phone:string;address:string}>(),db().prepare('SELECT weekday,enabled,opening,closing FROM weekly_hours ORDER BY weekday').all<Hours>()]);const map=new Map(hours.results.map(x=>[x.weekday,x]));return {profile:profile||{name:'Duu Jato',phone:'',address:''},hours:defaultHours.map(h=>map.get(h.weekday)||h)}}catch{return {profile:{name:'Duu Jato',phone:'',address:''},hours:defaultHours}}}
export async function generateMetadata():Promise<Metadata>{const {profile}=await business();return {title:`${profile.name} | Agendamento online`,description:`Agende a lavagem do seu veículo na ${profile.name}. Escolha serviço, data e horário.`,alternates:{canonical:BOOKING_URL}}}
export default async function Home(){const {profile,hours}=await business();const structured={ '@context':'https://schema.org','@type':'LocalBusiness',name:profile.name,url:BOOKING_URL,...(profile.address?{address:{'@type':'PostalAddress',streetAddress:profile.address}}:{}),...(profile.phone?{telephone:profile.phone}:{}),openingHoursSpecification:hours.filter(h=>h.enabled).map(h=>({'@type':'OpeningHoursSpecification',dayOfWeek:'https://schema.org/'+days[h.weekday],opens:h.opening,closes:h.closing}))};return <>{(profile.address||profile.phone)&&<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structured).replace(/</g,'\\u003c')}}/>}<Booking/></>}
